### ISSUE TITLE
It is transcribing only few words with warning generation\utils.py:1353: UserWarning: Using max_length's default (448)

### ISSUE THREAD

**Issue by junatgit** [shhossain/BanglaSpeech2Text#28]
At first, thanks a lot for creating this awesome library.

I am getting the following warning:
>\generation\utils.py:1353: UserWarning: Using `max_length`'s default (448) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.

And it is transcribing only first few words. How can I transcribe the whole file with 5 minutes of audio?
Note: I am using windows

**Comment by shhossain** [comment]
Speech2Text(max_new_tokens=?)

Play with max_new_tokens for longer audio.

**Comment by shhossain** [comment]
try with less like 512, 200, etc.

**Comment by r3v3r3seEntropy** [comment]
stt = Speech2Text("large", cache_path="cache", use_gpu=True, max_new_tokens = 512) this should work right?

**Comment by r3v3r3seEntropy** [comment]
it still doesn't transcribe a full 3 mins audio :(

**Comment by shhossain** [comment]
@r3v3r3seEntropy As i am not sure about your pc configuration i am not sure if it will work. but if you running it in free colab and it still crashes change use_gpu to device_map=“auto”

__Note__: you need to install accelerate for using auto. ‘pip install accelerate’

> it still doesn't transcribe a full 3 mins audio :(



> stt = Speech2Text("large", cache_path="cache", use_gpu=True, max_new_tokens = 512) this should work right?

@r3v3r3seEntropy, I'm uncertain about your PC configuration, so I can't guarantee that this solution will work for you. However, if you are running it in free Colab and it continues to crash, try changing the parameter "use_gpu" to "device_map='auto'".

Please note that in order to use "auto", you will need to install the "accelerate" package by running the command 'pip install accelerate'

**Comment by shhossain** [comment]
> it still doesn't transcribe a full 3 mins audio :(

try max_new_tokens 1024 with device map auto.

**Comment by r3v3r3seEntropy** [comment]
okay, can you suggest some other bangla speech to text ? which doesn't have limitation - can be paid

**Comment by shhossain** [comment]
> okay, can you suggest some other bangla speech to text ? which doesn't have limitation - can be paid

you can try google speech to text which supports bengali

**Comment by r3v3r3seEntropy** [comment]
Sorry to talk to you like this, can you see your facebook,,i sent you a text there

**Comment by shhossain** [comment]
See version 1.0.1 #30
